model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan_recon.VQModelwithSPRef
  params:
    embed_dim: 256
    n_embed: 1024
    noise_dim: 64
    ckpt_path: <coarse_prediction_model_path>
    use_memory: true
    clip_loss_weight: 0.75 # !!
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 87
      out_ch: 87
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: true
        disc_in_channels: 174
        disc_start: 0
        disc_weight: 0.8
        codebook_weight: 1
        rec_weight: 0.5
        div_weight: 0.25   # !!
    cliplossconfig:
      target: taming.modules.losses.clip.Loss
      params:
        device: cuda
        layout_clip:
          device: cuda
        shape_clip:
          device: cuda
          ckpt_path: <fine-tuned_clip_model_path>
          clip_model_name: ViT-B/32
          clip_conv_loss_type: L2
          clip_fc_loss_type: Cos
          clip_fc_loss_weight: 1
          clip_conv_layer_weights:
          - 0
          - 0
          - 0
          - 0
          - 0
          num_aug_clip: 0
        train_with_clip: false
        clip_weight: 0
        start_clip_iter: 0
        clip_conv_loss: 1
        clip_text_guide: 0
    recon_net:
      target: taming.models.shape_prior.AEModel
      params:
        in_channels: 1
        out_channels: 1
        num_hiddens: 8
        num_residual_hiddens: 4
        num_residual_layers: 2
        memory_refine: true
        memory_refine_k: 1
        ckpt_path: <context_bank_model_path>
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    num_workers: 1
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: <training_obj_list_path>
        training_images_dis_file: <training_gt_list_path>
        size: 128
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: <test_obj_list_path>
        test_images_dis_file: <test_obj_list_path>
        size: 128
